---
title: "predictionsMakingForStudyDesign"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(papaja)
```

$$
p(h | d) = \frac{ 1 - p( a | h ) }{ 1 - p(a|h)p(h) } p(h)
$$

## Contrasting different probability predictions

When both the $p(h)$ and $p(a)$ are 0.9, the equation predicts what is to me a surprisingly strong downgrade to each, namely down to 

```{r cars}
ph = .9
pa = .9
(1-ph)/(1-pa*ph) *ph
```

So what we could do is pair up two .9 factories (in the battery scenario), downgrade them, and compare to an undowngraded 0.9 and 0.6, which should win out!

##  Plots

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.height=4.2, fig.width=4.2,  fig.cap = "How belief in a central hypothesis should be decreased after a replication failure. Specifically, the plots shows the ratio of posterior to prior probability of the central hypothesis h as a function of the prior probability of the auxiliary hypothesis a,  for three different priors for the central hypothesis. Adapted from Strevens (2001)." }

expand.grid.df <- function(...) Reduce(function(...) merge(..., by=NULL), list(...))

x<- data.frame(x = seq(0,1,0.01) )
pH<- data.frame(ph = seq(0.1,0.9,0.2))
                
dg<-expand.grid.df( x, pH )

#mutate to calculate the ratio
library(dplyr)
dg<- mutate(dg, updateFactor = (1-x)/(1-x*ph))


library(ggplot2)
source( file.path("notesCalcs","theme_apa.R") ) #for calcFitDataframes

dg$ph <- factor(dg$ph)
g<-ggplot(dg,aes(x=x,y=updateFactor,color=ph)) + geom_line() +theme_apa()

g<-g +xlab(expression("p(a|h)"))
library(latex2exp)
#g + ylab( TeX('$\\alpha^\\beta$') )  
g<-g + ylab(    TeX('$\\frac{p( h | d ) }{ p (h) }$')   )   #always have to add backslash within string to interpret backslash

g<-g+ scale_color_discrete(guide=guide_legend(title="p(h)") )  #, legend.position=c(.1,.3), legend.background = element_rect())

changedTheme<- theme_apa() + theme(legend.position=c(0.19,0.36), legend.box.background = element_rect(color="grey"))
g<-g+ changedTheme

#g<-g+ theme(legend.position=c(.1,.3), legend.background = element_rect())
#Want to rotate y-axis label but that puts it at the top for some reason + theme(axis.title.y = element_text(angle=0))
plot(g)
```